[project]
name = "vigmykd-server"
version = "0.1.0"
description = "Game server for vigmykd"
authors = [
    { name = "discokitty", email = "vigmykd@runderscore.com" }
]
requires-python = ">=3.10"
dependencies = [
    "protobuf>=7.35.0",
    "pydantic-settings>=2.14.1",
    "python-dotenv>=1.2.2"
]

license = { file = "LICENSE" }

[project.optional-dependencies]
dev = [
    "flake8>=6.0",
    "mypy>=1.0",
    "pytest>=9.0.2",
    "httpx>=0.28.1"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
package-dir = {"" = "src"}