name: Bug Report
description: Report something that is broken or not working as expected
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug clearly
      placeholder: What is happening?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Press ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: media
    attributes:
      label: Screenshots / recordings
      description: Optional

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      options:
        - Always
        - Sometimes
        - Several times
        - Once

  - type: input
    id: os
    attributes:
      label: OS

  - type: input
    id: python
    attributes:
      label: Python version

  - type: input
    id: websockets
    attributes:
      label: websockets version

  - type: input
    id: commit
    attributes:
      label: Commit / branch

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/d1scocat/vigmykd-server/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true