syntax = "proto3";

package game.network;

message Ack {
    uint32 acknowledged_msg_id = 1;
    bool ok = 2;
}



enum Facing {
    FACING_NEG_X = 0;
    FACING_POS_X = 1;
}

message Position {
    Facing facing = 1;
    float x = 2;
    float y = 3;
}



message PlayerMoveState {
    uint32 client_tick = 1;

    uint32 move_dir = 2;
    bool duck = 3;
    bool jump = 4;
    bool dash = 5;
}


message RequestMatchInfo {
}

message PlayerData {
    string uuid = 1;
    string name = 2;
    Position position = 3;
}

message PositionData {
    string uuid = 1;
    Facing facing = 2;
    float x = 3;
    float vel_x = 4;
    float y = 5;
    float vel_y = 6;
    bool is_grounded = 7;
    bool is_dashing = 8;
    bool is_ducking = 9;
}

message RequestMatchInfoResponse {
    repeated PlayerData players = 1;
    string your_id = 2;
    uint64 rng_seed = 3;
    uint32 initial_server_tick = 4;
}

message Reconcile {
    repeated PositionData players = 1;
    uint32 server_tick = 2;
    uint32 last_client_tick = 3;
}



message MatchmakingEnter {
    string match_id = 1;
    string join_token = 2;
}

message MatchmakingEnterResponse {
    string match_id = 1;
}

message MatchmakingQuit {}

message MatchmakingQuitResponse {
    string match_id = 1;
}

message InformMatchStart {}



message ServerToClientPacket {
    // not bound to any id,
    // the packet wrapper handles those
    oneof payload {
        Ack ack = 1;

        Position position = 2;
        MatchmakingEnterResponse matchmaking_enter_response = 3;
        MatchmakingQuitResponse matchmaking_quit_response = 4;
        InformMatchStart inform_match_start = 5;
        RequestMatchInfoResponse request_match_info_response = 6;
        Reconcile reconcile = 7;
    }
}

message ClientToServerPacket {
    oneof payload {
        Ack ack = 1;

        PlayerMoveState player_move_state = 2;
        MatchmakingEnter matchmaking_enter = 3;
        MatchmakingQuit matchmaking_quit = 4;
        RequestMatchInfo request_match_info = 5;
    }
}

message InternalCommunicationPacket {
    message PlayerBrief {
        string id = 1;
        string name = 2;
    }

    message RegisterMatch {
        string match_id = 1;
        repeated PlayerBrief players = 2;
        string match_key = 3;
        string join_token = 4;
        uint64 expires = 5;
    }

    message RegisterMatchResponse {
        string joined_match_id = 1;
        string old_match_id = 2;
    }

    oneof payload {
        RegisterMatch register_match = 1;
        RegisterMatchResponse register_match_response = 2;
    }
}

message Packet {
    uint32 msg_id = 1;

    oneof payload {
        ServerToClientPacket server_to_client = 2;
        ClientToServerPacket client_to_server = 3;
        InternalCommunicationPacket icp = 4;
    }
}

message SignedPacket {
    Packet payload = 1;
    bytes signature = 2;
}

message Envelope {
    oneof payload {
        Packet packet = 1;
        SignedPacket signed_packet = 2;
    }
}