syntax = "proto3";

package game.network;

message Ack {
    uint32 acknowledged_msg_id = 1;
    bool ok = 2;
}



enum Facing {
    FACING_NEG_X = 0;
    FACING_POS_X = 1;
}

message Position {
    Facing facing = 1;
    float x = 2;
    float y = 3;
}



message PlayerMove {
    enum Type {
        TYPE_JUMP = 0;
    }

    Type type = 1;
}



message MatchmakingEnter {
    string match_id = 1;
    string join_token = 2;
}

message MatchmakingQuit {}



message ServerToClientPacket {
    // not bound to any id,
    // the packet wrapper handles those
    oneof payload {
        Ack ack = 1;

        Position position = 2;
    }
}

message ClientToServerPacket {
    oneof payload {
        PlayerMove player_action = 1;

        MatchmakingEnter matchmaking_enter = 2;
        MatchmakingQuit matchmaking_quit = 3;
    }
}

message InternalCommunicationPacket {
    message RegisterMatch {
        string match_id = 1;
        repeated string players = 2;
        string match_key = 3;
        string join_token = 4;
        uint64 expires = 5;
    }

    message RegisterMatchResponse {
        string joined_match_id = 1;
        string old_match_id = 2;
    }

    oneof payload {
        RegisterMatch register_match = 1;
        RegisterMatchResponse register_match_response = 2;
    }
}

message RespondBack {
    string reply_host = 1;
    uint32 reply_port = 2;
}

message Packet {
    uint32 msg_id = 1;

    oneof payload {
        ServerToClientPacket server_to_client = 2;
        ClientToServerPacket client_to_server = 3;
        InternalCommunicationPacket icp = 4;
    }

    optional RespondBack reply_back = 5;
}

message SignedPacket {
    Packet payload = 1;
    bytes signature = 2;
}

message Envelope {
    oneof payload {
        Packet packet = 1;
        SignedPacket signed_packet = 2;
    }
}